
services:
  postgres:
    image: 'postgres:13.3'
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    volumes:
      - ./ci/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8281:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./ci/servers.json:/pgadmin4/servers.json
      - ./ci/pgpassfile:/pgpassfile
    depends_on:
      - postgres